apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-client
  namespace: dev
  labels:
    app: client
spec:
  containers:
  - name: alpine
    image: alpine:3.20
    command: ["sh", "-c", "sleep 3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: apache-server
  namespace: dev
  labels:
    app: web
spec:
  containers:
  - name: apache
    image: httpd:2.4-alpine
    ports:
    - containerPort: 80
      protocol: TCP
