apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql_app
spec:
  serviceName: mysql_service
  replicas: 1
  selector:
    app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql_app
        image: mysql
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 12345678
        volumeMounts:
        - name: mysql_volume
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql_volume
    spec:
      resources:
        requests:
          storage: 1Gi
      storageClassName: db_storage
      accessModes:
      - ReadWriteOnce
