apiVersion: v1
kind: Namespace
metadata:
  name: jupiter
---
apiVersion: v1
kind: Namespace
metadata:
  name: saturn
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: saturn
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    command: ["sh", "-c", "tail -f /dev/null"]
---
apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  namespace: jupiter
  labels:
    app: api
spec:
  containers:
  - name: api-container
    image: python:3.12-alpine
    command: ["python"]
    args: ["-m", "http.server", "5000"]
    ports:
    - containerPort: 5000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: metrics-exporter
  namespace: jupiter
  labels:
    app: metrics
spec:
  containers:
  - name: exporter
    image: prom/node-exporter:latest
    ports:
    - containerPort: 9100
