#api
apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    service: api
spec:
  containers:
  - name: api
    image: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Never


---

#auth
apiVersion: v1
kind: Pod
metadata:
  name: auth
  labels:
    service: auth
spec:
  containers:
  - name: auth
    image: busybox
    command: ["sleep", "3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never


---

#logger
apiVersion: v1
kind: Pod
metadata:
  name: logger
  labels:
    service: logger
spec:
  containers:
  - name: logger
    image: busybox
    command: ["sleep", "3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never


---

#db
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    service: db
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "12345678"
  dnsPolicy: ClusterFirst
  restartPolicy: Never

