apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-client
  namespace: prod
  labels:
    app: frontend
spec:
  containers:
  - name: curl
    image: curlimages/curl:8.8.0
    command: ["sh", "-c", "sleep 3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: caddy-server
  namespace: prod
  labels:
    app: backend
spec:
  containers:
  - name: caddy
    image: caddy:2.8.4-alpine
    ports:
    - containerPort: 80
      protocol: TCP
