# backend-v2-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-v2
  template:
    metadata:
      labels:
        app: backend-v2
    spec:
      containers:
        - name: backend
          image: python:3.11-slim
          command: ["python", "-m", "http.server", "5000"]
          ports:
            - containerPort: 5000

---

# backend-v1-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-v1
  template:
    metadata:
      labels:
        app: backend-v1
    spec:
      containers:
        - name: backend
          image: python:3.11-slim
          command: ["python", "-m", "http.server", "8080"]
          ports:
            - containerPort: 8080

---

# frontend-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://backend-hybrid:8080"
